In [36]:
#Cau1
a = float(input("Nhập giá trị cho a: "))
b = float(input("Nhập giá trị cho b: "))
# Tính tổng
tong = a + b
# Tính hiệu
hieu = a - b
# Tính tích
tich = a * b
# Tính thương (kiểm tra chia cho 0)
if b != 0:
    thuong = a / b
else:
    thuong = "Không thể chia cho 0"
# In kết quả
print(f"Tổng của {a} và {b} là: {tong}")
print(f"Hiệu của {a} và {b} là: {hieu}")
print(f"Tích của {a} và {b} là: {tich}")
print(f"Thương của {a} và {b} là: {thuong}")

Nhập giá trị cho a: 34236
Nhập giá trị cho b: 2536456
Tổng của 34236.0 và 2536456.0 là: 2570692.0
Hiệu của 34236.0 và 2536456.0 là: -2502220.0
Tích của 34236.0 và 2536456.0 là: 86838107616.0
Thương của 34236.0 và 2536456.0 là: 0.013497572991607188


In [ ]:
#Cau2
chuoi = "Hello World"
ky_tu_da_cat = chuoi[2:5] # Lấy ký tự từ chỉ số 2 đến chỉ số 4
print(ky_tu_da_cat)

llo


In [ ]:
#Cau3
chuoi_goc = "   Hello World   "
print(f"Chuỗi gốc: '{chuoi_goc}'")
# 1. Xóa khoảng trắng thừa ở đầu và cuối chuỗi
chuoi_da_cat_khoang_trang = chuoi_goc.strip()
print(f"Chuỗi sau khi cắt khoảng trắng: '{chuoi_da_cat_khoang_trang}'")
# 2. Chuyển chuỗi sang dạng hoa
chuoi_hoa = chuoi_da_cat_khoang_trang.upper()
print(f"Chuỗi dạng hoa: '{chuoi_hoa}'")
# 3. Chuyển chuỗi sang dạng thường
chuoi_thuong = chuoi_da_cat_khoang_trang.lower()
print(f"Chuỗi dạng thường: '{chuoi_thuong}'")
# 4. Thay ký tự H thành ký tự J
chuoi_thay_the_H_thanh_J = chuoi_da_cat_khoang_trang.replace('H', 'J')
print(f"Chuỗi sau khi thay 'H' bằng 'J': '{chuoi_thay_the_H_thanh_J}'")

Chuỗi gốc: '   Hello World   '
Chuỗi sau khi cắt khoảng trắng: 'Hello World'
Chuỗi dạng hoa: 'HELLO WORLD'
Chuỗi dạng thường: 'hello world'
Chuỗi sau khi thay 'H' bằng 'J': 'Jello World'


In [ ]:
a = float(input("Nhập giá trị cho a: "))
b = float(input("Nhập giá trị cho b: "))
c = float(input("Nhập giá trị cho c: "))
d = float(input("Nhập giá trị cho d: "))

print("\n--- Kết quả kiểm tra điều kiện ---")

#Cau4. In ra “Hello World!” nếu a lớn hơn b.
if a > b:
    print("Hello World!")
else:
    print("a không lớn hơn b.")

#Cau5. In ra “Yes” nếu a bằng b, ngược lại in “No”.
if a == b:
    print("Yes")
else:
    print("No")

#Cau6. In 1 nếu a bằng b, in 2 nếu a > b, in 3 nếu ngược lại.
if a == b:
    print(1)
elif a > b:
    print(2)
else:
    print(3)

#Cau7. In ra “Hello World!” nếu a bằng b và b bằng d.
if a == b and b == d:
    print("Hello World!")
else:
    print("Điều kiện a==b và b==d không đúng.")

#Cau8. In ra “Hello World!” nếu a bằng b hoặc c bằng d.
if a == b or c == d:
    print("Hello World!")
else:
    print("Điều kiện a==b hoặc c==d không đúng.")

In [ ]:

#Cau 9
a = float(input("Nhập giá trị cho a: "))
b = float(input("Nhập giá trị cho b: "))

print('yes') if a > b else print('no')
print("A") if a > b else print("=") if a == b else print("B")

Nhập giá trị cho a: 5
Nhập giá trị cho b: 3
yes
A


In [33]:
#Cau 10
a = float(input("Nhập giá trị cho a: "))
b = float(input("Nhập giá trị cho b: "))
if a > b :
  print("A")
else :
  print("=")
if a == b :
  print ("=")
else :
  print("B")

Nhập giá trị cho a: 6
Nhập giá trị cho b: 3
A
B


In [34]:
#Cau11
# Nhập số lượng phần tử cho mảng a
while True:
    try:
        n = int(input("Nhập số lượng phần tử (n) cho mảng a: "))
        if n <= 0:
            print("Số lượng phần tử phải là số nguyên dương. Vui lòng nhập lại.")
        else:
            break
    except ValueError:
        print("Đầu vào không hợp lệ. Vui lòng nhập một số nguyên.")
# Tạo mảng a với n phần tử
a = []
print(f"\nVui lòng nhập {n} số nguyên cho mảng a:")
for i in range(n):
    while True:
        try:
            element = int(input(f"Nhập phần tử thứ {i+1}: "))
            a.append(element)
            break
        except ValueError:
            print("Đầu vào không hợp lệ. Vui lòng nhập một số nguyên.")
# Tạo mảng b chỉ chứa các phần tử chẵn của a
b = []
for element in a:
    if element % 2 == 0:
        b.append(element)
# In kết quả
print(f"\nMảng a đã tạo là: {a}")
print(f"Mảng b (chỉ chứa các phần tử chẵn của a) là: {b}")

Nhập số lượng phần tử (n) cho mảng a: 4

Vui lòng nhập 4 số nguyên cho mảng a:
Nhập phần tử thứ 1: 4
Nhập phần tử thứ 2: 2
Nhập phần tử thứ 3: 5
Nhập phần tử thứ 4: 7

Mảng a đã tạo là: [4, 2, 5, 7]
Mảng b (chỉ chứa các phần tử chẵn của a) là: [4, 2]


In [35]:
#Cau12
# Khởi tạo tổng
tong_boi = 0
# Lặp qua các số từ 0 đến 999
for i in range(1000):
    # Kiểm tra nếu số đó là bội của 3 hoặc 5
    if i % 3 == 0 or i % 5 == 0:
        tong_boi += i

# In kết quả
print(f"Tổng các số từ 0 đến 999 mà là bội của 3 hoặc 5 là: {tong_boi}")

Tổng các số từ 0 đến 999 mà là bội của 3 hoặc 5 là: 233168


In [ ]:
#Cau13
def merge_arrays_with_sum_and_remainder(arr1, arr2):
    """
    Trộn 2 mảng một chiều thành 1 mảng một chiều.
    Mỗi phần tử của mảng mới là tổng của 2 phần tử tương ứng từ 2 mảng cho trước
    cho đến khi một trong hai mảng hết phần tử.
    Các phần tử còn lại của mảng dài hơn sẽ được đưa vào mảng mới.

    Args:
        arr1 (list): Mảng thứ nhất.
        arr2 (list): Mảng thứ hai.

    Returns:
        list: Mảng kết quả đã trộn.
    """
    result = []
    len1 = len(arr1)
    len2 = len(arr2)
    min_len = min(len1, len2)

    # Tính tổng các phần tử tương ứng cho đến hết mảng ngắn hơn
    for i in range(min_len):
        result.append(arr1[i] + arr2[i])

    # Thêm các phần tử còn lại của mảng dài hơn vào kết quả
    if len1 > len2:
        result.extend(arr1[min_len:])
    elif len2 > len1:
        result.extend(arr2[min_len:])

    return result

# Ví dụ sử dụng dựa trên mô tả
a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]
merged_result = merge_arrays_with_sum_and_remainder(a, b)
print(f"Mảng a: {a}")
print(f"Mảng b: {b}")
print(f"Mảng kết quả (theo mô tả): {merged_result}")

# Các trường hợp kiểm tra khác
# Trường hợp mảng arr1 dài hơn
c = [10, 20, 30, 40, 50]
d = [1, 2, 3]
merged_result_c_d = merge_arrays_with_sum_and_remainder(c, d)
print(f"\nMảng c: {c}")
print(f"Mảng d: {d}")
print(f"Mảng kết quả (c, d): {merged_result_c_d}")

# Trường hợp hai mảng có cùng độ dài
e = [1, 2, 3]
f = [4, 5, 6]
merged_result_e_f = merge_arrays_with_sum_and_remainder(e, f)
print(f"\nMảng e: {e}")
print(f"Mảng f: {f}")
print(f"Mảng kết quả (e, f): {merged_result_e_f}")

# Trường hợp có mảng rỗng
g = []
h = [1, 2, 3]
merged_result_g_h = merge_arrays_with_sum_and_remainder(g, h)
print(f"\nMảng g: {g}")
print(f"Mảng h: {h}")
print(f"Mảng kết quả (g, h): {merged_result_g_h}")

In [10]:
#cau14
import numpy as np

def create_random_2d_array(m, n, min_val=0, max_val=100):
    """
    Tạo một mảng 2 chiều có m dòng, n cột chứa các số nguyên ngẫu nhiên.

    Args:
        m (int): Số lượng dòng.
        n (int): Số lượng cột.
        min_val (int): Giá trị nhỏ nhất của số nguyên ngẫu nhiên (bao gồm).
        max_val (int): Giá trị lớn nhất của số nguyên ngẫu nhiên (không bao gồm).

    Returns:
        np.ndarray: Mảng 2 chiều chứa các số nguyên ngẫu nhiên.
    """
    if m <= 0 or n <= 0:
        raise ValueError("Số dòng (m) và số cột (n) phải là số nguyên dương.")

    # Sử dụng np.random.randint để tạo mảng số nguyên ngẫu nhiên
    random_array = np.random.randint(min_val, max_val, size=(m, n))
    return random_array

print("Hàm `create_random_2d_array` đã được định nghĩa.")
# Ví dụ sử dụng hàm với m và n đã cho trong kernel (m_large, n_large)
# Giả sử m_large và n_large đã được định nghĩa từ trước, ví dụ: m_large = 5, n_large = 5

# Lấy giá trị m và n từ kernel state
m = m_large # m_large = 5 từ kernel state
n = n_large # n_large = 5 từ kernel state

print(f"Tạo mảng 2 chiều với {m} dòng và {n} cột:")
a = create_random_2d_array(m, n, min_val=1, max_val=50) # Ví dụ tạo số từ 1 đến 49
print(a)

Hàm `create_random_2d_array` đã được định nghĩa.
Tạo mảng 2 chiều với 5 dòng và 5 cột:
[[ 8  4 24 35 44]
 [13 21 26 16  5]
 [18 36 31 11  5]
 [18  9 35  8  4]
 [39 37 49  4 12]]


In [9]:
#Cau14: a.Xuất các phần tử thuộc dòng k

# Kiểm tra xem mảng 'a' có tồn tại trong kernel không
if 'a' not in locals() and 'a' not in globals():
    print("Mảng 'a' chưa được tạo. Vui lòng chạy lại các ô trước để tạo mảng 'a'.")
else:
    print(f"Mảng 'a' hiện tại:\n{a}")
    num_rows = a.shape[0]
    while True:
        try:
            k = int(input(f"Nhập chỉ số dòng k (từ 0 đến {num_rows - 1}) để xuất các phần tử: "))
            if 0 <= k < num_rows:
                break
            else:
                print(f"Chỉ số dòng k không hợp lệ. Vui lòng nhập số nguyên từ 0 đến {num_rows - 1}.")
        except ValueError:
            print("Đầu vào không hợp lệ. Vui lòng nhập một số nguyên.")
    # Xuất các phần tử thuộc dòng k
    row_k = a[k, :]
    print(f"Các phần tử thuộc dòng {k} là: {row_k}")

Mảng 'a' hiện tại:
[[ 9 20 44 40 47]
 [47  8  6 10  9]
 [48 34  5 32 28]
 [49 17  8 48 22]
 [35 23 14  4 14]]
Nhập chỉ số dòng k (từ 0 đến 4) để xuất các phần tử: 4
Các phần tử thuộc dòng 4 là: [35 23 14  4 14]


In [11]:
#Cau14: b. Xuất các phần tử thuộc cột k

# Kiểm tra xem mảng 'a' có tồn tại trong kernel không
if 'a' not in locals() and 'a' not in globals():
    print("Mảng 'a' chưa được tạo. Vui lòng chạy lại các ô trước để tạo mảng 'a'.")
else:
    print(f"Mảng 'a' hiện tại:\n{a}")
    num_cols = a.shape[1]

    while True:
        try:
            k = int(input(f"Nhập chỉ số cột k (từ 0 đến {num_cols - 1}) để xuất các phần tử: "))
            if 0 <= k < num_cols:
                break
            else:
                print(f"Chỉ số cột k không hợp lệ. Vui lòng nhập số nguyên từ 0 đến {num_cols - 1}.")
        except ValueError:
            print("Đầu vào không hợp lệ. Vui lòng nhập một số nguyên.")

    # Xuất các phần tử thuộc cột k
    col_k = a[:, k]
    print(f"Các phần tử thuộc cột {k} là: {col_k}")

Mảng 'a' hiện tại:
[[ 8  4 24 35 44]
 [13 21 26 16  5]
 [18 36 31 11  5]
 [18  9 35  8  4]
 [39 37 49  4 12]]
Nhập chỉ số cột k (từ 0 đến 4) để xuất các phần tử: 4
Các phần tử thuộc cột 4 là: [44  5  5  4 12]


In [ ]:
#Cau14: c. Tìm dòng có tổng lớn nhất và d. Tìm cột có tích nhỏ nhất

# Kiểm tra xem mảng 'a' có tồn tại trong kernel không
if 'a' not in locals() and 'a' not in globals():
    print("Mảng 'a' chưa được tạo. Vui lòng chạy lại các ô trước để tạo mảng 'a'.")
else:
    print(f"Mảng 'a' hiện tại:\n{a}")

    # c. Tìm dòng có tổng lớn nhất
    row_sums = np.sum(a, axis=1) # Tính tổng từng dòng
    max_sum_row_index = np.argmax(row_sums) # Tìm chỉ số của dòng có tổng lớn nhất
    max_sum_row = a[max_sum_row_index, :]
    print(f"\nDòng có tổng lớn nhất là dòng {max_sum_row_index} với tổng = {row_sums[max_sum_row_index]}: {max_sum_row}")

    # d. Tìm cột có tích nhỏ nhất
    # Sử dụng np.prod để tránh tràn số với các số lớn, nếu mảng chứa các giá trị rất lớn.
    # Tuy nhiên, nếu mảng chứa 0, tích sẽ là 0, điều này có thể ảnh hưởng đến kết quả.
    # Đảm bảo các giá trị trong mảng không âm để tích có ý nghĩa khi so sánh nhỏ nhất.
    column_products = np.prod(a, axis=0) # Tính tích từng cột
    min_prod_col_index = np.argmin(column_products) # Tìm chỉ số của cột có tích nhỏ nhất
    min_prod_col = a[:, min_prod_col_index]
    print(f"Cột có tích nhỏ nhất là cột {min_prod_col_index} với tích = {column_products[min_prod_col_index]}: {min_prod_col}")

In [ ]:
#Cau14: e. Xuất các phần tử thuộc dòng chẵn và cột lẻ

# Kiểm tra xem mảng 'a' có tồn tại trong kernel không
if 'a' not in locals() and 'a' not in globals():
    print("Mảng 'a' chưa được tạo. Vui lòng chạy lại các ô trước để tạo mảng 'a'.")
else:
    print(f"Mảng 'a' hiện tại:\n{a}")

    # Lấy các dòng có chỉ số chẵn (0, 2, 4, ...)
    # và các cột có chỉ số lẻ (1, 3, 5, ...)
    elements_even_rows_odd_cols = a[::2, 1::2]
    print("\nCác phần tử thuộc dòng chẵn và cột lẻ:")
    print(elements_even_rows_odd_cols)

In [ ]:
#Cau14: f. Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ của a

# Kiểm tra xem mảng 'a' có tồn tại trong kernel không
if 'a' not in locals() and 'a' not in globals():
    print("Mảng 'a' chưa được tạo. Vui lòng chạy lại các ô trước để tạo mảng 'a'.")
else:
    print(f"Mảng 'a' hiện tại:\n{a}")

    # Lấy các dòng có chỉ số lẻ (1, 3, 5, ...)
    odd_rows = a[1::2, :]
    print(f"\nCác dòng lẻ:\n{odd_rows}")

    # Lọc ra các phần tử chẵn từ các dòng lẻ
    even_elements_in_odd_rows = odd_rows[odd_rows % 2 == 0]

    if even_elements_in_odd_rows.size > 0:
        average = np.mean(even_elements_in_odd_rows)
        print(f"Các phần tử chẵn thuộc dòng lẻ: {even_elements_in_odd_rows}")
        print(f"Trung bình cộng các phần tử chẵn thuộc dòng lẻ là: {average:.2f}")
    else:
        print("Không có phần tử chẵn nào thuộc dòng lẻ.")

In [13]:
#Cau14: g. Tính trung bình cộng các phần tử thuộc biên và h. Tính tích các phần tử không thuộc biên

# Kiểm tra xem mảng 'a' có tồn tại trong kernel không
if 'a' not in locals() and 'a' not in globals():
    print("Mảng 'a' chưa được tạo. Vui lòng chạy lại các ô trước để tạo mảng 'a'.")
else:
    print(f"Mảng 'a' hiện tại:\n{a}")

    num_rows, num_cols = a.shape

    # g. Tính trung bình cộng các phần tử thuộc biên
    if num_rows == 0 or num_cols == 0:
        print("\nMảng rỗng, không có phần tử biên.")
        average_border = None
    else:
        # Tạo một mask boolean để đánh dấu các phần tử biên
        border_mask = np.full(a.shape, False, dtype=bool)
        border_mask[0, :] = True  # Hàng đầu tiên
        border_mask[-1, :] = True # Hàng cuối cùng
        border_mask[:, 0] = True  # Cột đầu tiên
        border_mask[:, -1] = True # Cột cuối cùng

        border_elements = a[border_mask]

        if border_elements.size > 0:
            average_border = np.mean(border_elements)
            print(f"\nCác phần tử thuộc biên là: {border_elements}")
            print(f"Trung bình cộng các phần tử thuộc biên là: {average_border:.2f}")
        else:
            print("\nKhông có phần tử biên (ví dụ: mảng 1x1).")
            average_border = None

    # h. Tính tích các phần tử không thuộc biên
    # Các phần tử không thuộc biên là a[1:-1, 1:-1]
    # Slicing a[1:-1, 1:-1] sẽ trả về mảng rỗng nếu num_rows < 3 hoặc num_cols < 3
    if num_rows < 3 or num_cols < 3:
        print("\nKích thước mảng quá nhỏ, không có phần tử không thuộc biên.")
        product_non_border = None
    else:
        non_border_elements = a[1:-1, 1:-1]
        if non_border_elements.size > 0:
            product_non_border = np.prod(non_border_elements)
            print(f"\nCác phần tử không thuộc biên là:\n{non_border_elements}")
            print(f"Tích các phần tử không thuộc biên là: {product_non_border}")
        else:
            print("\nKhông có phần tử không thuộc biên (có thể do kích thước mảng không đủ lớn sau khi cắt).")
            product_non_border = None

Mảng 'a' hiện tại:
[[ 8  4 24 35 44]
 [13 21 26 16  5]
 [18 36 31 11  5]
 [18  9 35  8  4]
 [39 37 49  4 12]]

Các phần tử thuộc biên là: [ 8  4 24 35 44 13  5 18  5 18  4 39 37 49  4 12]
Trung bình cộng các phần tử thuộc biên là: 19.94

Các phần tử không thuộc biên là:
[[21 26 16]
 [36 31 11]
 [ 9 35  8]]
Tích các phần tử không thuộc biên là: 270252702720


In [17]:
#cau15
class SINHVIEN:
    def __init__(self, ma_sinh_vien, ten, nam_sinh, diem_trung_binh):
        # 1. Mã sinh viên là chuỗi có 10 ký tự
        if not isinstance(ma_sinh_vien, str) or len(ma_sinh_vien) != 10:
            raise ValueError("Mã sinh viên phải là chuỗi có đúng 10 ký tự.")
        self.ma_sinh_vien = ma_sinh_vien
        # 2. Tên là chuỗi tối đa 20 ký tự
        if not isinstance(ten, str) or len(ten) > 20:
            raise ValueError("Tên phải là chuỗi và không quá 20 ký tự.")
        self.ten = ten
        # 3. Năm sinh là một số nguyên
        if not isinstance(nam_sinh, int):
            raise ValueError("Năm sinh phải là một số nguyên.")
        self.nam_sinh = nam_sinh
        # 4. Điểm trung bình là một số thực
        if not isinstance(diem_trung_binh, (int, float)):
            raise ValueError("Điểm trung bình phải là một số thực.")
        self.diem_trung_binh = float(diem_trung_binh)
    def __str__(self):
        return (f"Mã sinh viên: {self.ma_sinh_vien}\n" +
                f"Tên: {self.ten}\n" +
                f"Năm sinh: {self.nam_sinh}\n" +
                f"Điểm trung bình: {self.diem_trung_binh:.2f}")

print("Cấu trúc SINHVIEN đã được định nghĩa.")

# Ví dụ sử dụng cấu trúc SINHVIEN
try:
    sv1 = SINHVIEN("SV00000001", "Nguyễn Văn A", 2002, 8.5)
    print("\n--- Thông tin sinh viên 1 ---")
    print(sv1)

    sv2 = SINHVIEN("SV00000002", "Trần Thị Bích Vân", 2003, 7.85)
    print("\n--- Thông tin sinh viên 2 ---")
    print(sv2)

    # Ví dụ với dữ liệu không hợp lệ (mã sinh viên sai độ dài)
    # sv_error_ma = SINHVIEN("SV001", "Lỗi Mã", 2000, 6.0)
    # print(sv_error_ma)

    # Ví dụ với dữ liệu không hợp lệ (tên quá dài)
    # sv_error_ten = SINHVIEN("SV00000003", "Phạm Minh Khôi An Ninh", 2001, 9.2)
    # print(sv_error_ten)

except ValueError as e:
    print(f"\nLỗi khi tạo sinh viên: {e}")

Cấu trúc SINHVIEN đã được định nghĩa.

--- Thông tin sinh viên 1 ---
Mã sinh viên: SV00000001
Tên: Nguyễn Văn A
Năm sinh: 2002
Điểm trung bình: 8.50

--- Thông tin sinh viên 2 ---
Mã sinh viên: SV00000002
Tên: Trần Thị Bích Vân
Năm sinh: 2003
Điểm trung bình: 7.85


In [24]:
#Cau15: Viết hàm đếm sinh viên đủ điều kiện lên lớp

def dem_sinh_vien_du_dieu_kien(danh_sach_sinh_vien):
    """
    Đếm số lượng sinh viên đủ điều kiện lên lớp (điểm trung bình >= 5).

    Args:
        danh_sach_sinh_vien (list): Danh sách các đối tượng SINHVIEN.

    Returns:
        int: Số lượng sinh viên đủ điều kiện.
    """
    so_luong_du_dieu_kien = 0
    for sv in danh_sach_sinh_vien:
        if sv.diem_trung_binh >= 5.0:
            so_luong_du_dieu_kien += 1
    return so_luong_du_dieu_kien

# Tạo một danh sách sinh viên mẫu để kiểm tra
try:
    ds_sv = [
        SINHVIEN("SV00000001", "Nguyễn Văn A", 2002, 8.5),
        SINHVIEN("SV00000002", "Trần Thị Bích Vân", 2003, 4.8),
        SINHVIEN("SV00000003", "Phan Văn C", 2004, 6.2),
        SINHVIEN("SV00000004", "Phạm Thị D", 2005, 9.1),
        SINHVIEN("SV00000005", "Hoàng Minh E", 2000, 3.5),
        SINHVIEN("SV00000006", "Phan Thị Lan", 2003, 7.0)
    ]
    print("\n--- Danh sách sinh viên mẫu đã tạo ---")
    for sv in ds_sv:
        print(f"  - {sv.ten} (Điểm TB: {sv.diem_trung_binh})")

    # Sử dụng hàm để đếm sinh viên đủ điều kiện
    so_luong_dat = dem_sinh_vien_du_dieu_kien(ds_sv)
    print(f"\nSố lượng sinh viên đủ điều kiện lên lớp: {so_luong_dat}")

except ValueError as e:
    print(f"\nLỗi khi tạo danh sách sinh viên: {e}")


--- Danh sách sinh viên mẫu đã tạo ---
  - Nguyễn Văn A (Điểm TB: 8.5)
  - Trần Thị Bích Vân (Điểm TB: 4.8)
  - Phan Văn C (Điểm TB: 6.2)
  - Phạm Thị D (Điểm TB: 9.1)
  - Hoàng Minh E (Điểm TB: 3.5)
  - Phan Thị Lan (Điểm TB: 7.0)

Số lượng sinh viên đủ điều kiện lên lớp: 4


In [25]:
#Cau15: Xuất các sinh viên đủ 20 tuổi trở lên

# Giả sử năm hiện tại là 2024 để tính tuổi
NAM_HIEN_TAI = 2026

print(f"\n--- Danh sách sinh viên đủ 20 tuổi trở lên (năm hiện tại: {NAM_HIEN_TAI}) ---")
found_students = False
for sv in ds_sv:
    tuoi = NAM_HIEN_TAI - sv.nam_sinh
    if tuoi >= 20:
        print(sv)
        print("--------------------")
        found_students = True

if not found_students:
    print("Không có sinh viên nào đủ 20 tuổi trở lên trong danh sách.")


--- Danh sách sinh viên đủ 20 tuổi trở lên (năm hiện tại: 2026) ---
Mã sinh viên: SV00000001
Tên: Nguyễn Văn A
Năm sinh: 2002
Điểm trung bình: 8.50
--------------------
Mã sinh viên: SV00000002
Tên: Trần Thị Bích Vân
Năm sinh: 2003
Điểm trung bình: 4.80
--------------------
Mã sinh viên: SV00000003
Tên: Phan Văn C
Năm sinh: 2004
Điểm trung bình: 6.20
--------------------
Mã sinh viên: SV00000004
Tên: Phạm Thị D
Năm sinh: 2005
Điểm trung bình: 9.10
--------------------
Mã sinh viên: SV00000005
Tên: Hoàng Minh E
Năm sinh: 2000
Điểm trung bình: 3.50
--------------------
Mã sinh viên: SV00000006
Tên: Phan Thị Lan
Năm sinh: 2003
Điểm trung bình: 7.00
--------------------


In [26]:
#Cau15: Đếm số sinh viên học hệ đại học (mã sinh viên chứa 'DH' ở vị trí 2,3)

# Đảm bảo ds_sv đã được tạo từ các ô trước
if 'ds_sv' not in locals() and 'ds_sv' not in globals():
    print("Danh sách sinh viên 'ds_sv' chưa được tạo. Vui lòng chạy lại các ô trước.")
else:
    so_luong_dh = 0
    for sv in ds_sv:
        # Kiểm tra độ dài mã sinh viên trước để tránh lỗi index out of range
        if len(sv.ma_sinh_vien) >= 4 and sv.ma_sinh_vien[2:4] == "DH":
            so_luong_dh += 1

    print(f"\nSố lượng sinh viên học hệ Đại học (có 'DH' tại vị trí 2,3 trong mã SV): {so_luong_dh}")


Số lượng sinh viên học hệ Đại học (có 'DH' tại vị trí 2,3 trong mã SV): 0


In [27]:
#Cau15: Đếm số sinh viên có tên 'Lan'

if 'ds_sv' not in locals() and 'ds_sv' not in globals():
    print("Danh sách sinh viên 'ds_sv' chưa được tạo. Vui lòng chạy lại các ô trước.")
else:
    so_luong_ten_lan = 0
    for sv in ds_sv:
        # Tách tên và lấy phần cuối cùng (giả sử là tên)
        ten_list = sv.ten.split()
        if ten_list and ten_list[-1].lower() == "lan":
            so_luong_ten_lan += 1

    print(f"\nSố lượng sinh viên có tên 'Lan': {so_luong_ten_lan}")


Số lượng sinh viên có tên 'Lan': 1


In [28]:
#Cau15: Đếm số sinh viên có họ 'Phan'

if 'ds_sv' not in locals() and 'ds_sv' not in globals():
    print("Danh sách sinh viên 'ds_sv' chưa được tạo. Vui lòng chạy lại các ô trước.")
else:
    so_luong_ho_phan = 0
    for sv in ds_sv:
        # Tách tên và lấy phần đầu tiên (giả sử là họ)
        ten_list = sv.ten.split()
        if ten_list and ten_list[0].lower() == "phan":
            so_luong_ho_phan += 1

    print(f"\nSố lượng sinh viên có họ 'Phan': {so_luong_ho_phan}")


Số lượng sinh viên có họ 'Phan': 2
